import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main>Loading...</main>;
  }

  return (
    <>
      <Head>
        <title>Poll App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Hello there</h1>

          {session ? (
            <div>
              <p>hi {session.user?.name}</p>

              <button onClick={() => signOut()}>Logout</button>
            </div>
          ) : (
            <div>
              <button onClick={() => signIn("discord")}>
                Login with Discord
              </button>
            </div>
          )}
        </div>
        <span className="text-green-500">{hello.data?.greeting}</span>
      </main>
    </>
  );
};

export default Home;
